export const exampleStyle = {
  version: 8,
  name: 'SZ_BaseMap',
  sources: {
    QG_BaseMap: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/QG_BaseMap%3AQG_BaseMap@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        -180.00018310499996,
        -89.99999999999994,
        180.0000000000001,
        85.07598389300006,
      ],
    },
    CSS_BaseMap: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3ACSS_BaseMap@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.538597106934,
        31.4949398040771,
        121.100685119629,
        31.8708190917969,
      ],
    },
    xzqh_qxjxzq_p: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3Axzqh_qxjxzq_p@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.538597106934,
        31.4949398040771,
        121.100685119629,
        31.8708190917969,
      ],
    },
    xzqh_qxjxzq_b_300: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3Axzqh_qxjxzq_b_300@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.532272338867,
        31.4895286560059,
        121.107025146484,
        31.8762302398682,
      ],
    },
    xzqh_zrc_pt: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3Axzqh_zrc_pt@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.539535522461,
        31.4977226257324,
        121.064895629883,
        31.8328628540039,
      ],
    },
    xqd_poi_pt: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3Axqd_poi_pt@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.543884277344,
        31.4987182617188,
        121.055297851563,
        31.8438720703125,
      ],
    },
    ld_gy_p: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3Ald_gy_p@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.590339660645,
        31.5059452056885,
        120.969573974609,
        31.7792072296143,
      ],
    },
    sx_sx_p: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3Asx_sx_p@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.538604736328,
        31.4950275421143,
        121.100685119629,
        31.8708190917969,
      ],
    },
    sx_sx_pt: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3Asx_sx_pt@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.540367126465,
        31.5003986358643,
        121.060806274414,
        31.8252983093262,
      ],
    },
    ld_ld_p_nb: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3Ald_ld_p_nb@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.541030883789,
        31.4983501434326,
        121.06519317627,
        31.8321628570557,
      ],
    },
    ld_ld_p_fnb: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3Ald_ld_p_fnb@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.541030883789,
        31.4983501434326,
        121.06519317627,
        31.8321628570557,
      ],
    },
    jgzw_jzw_p: {
      tiles: [
        'http://36.153.213.20/geoenginev2/geoserver/gwc/service/tms/1.0.0/CSS_BaseMap%3Ajgzw_jzw_p@EPSG%3A4326@pbf/{z}/{x}/{y}.pbf',
      ],
      zoomOffset: -1,
      type: 'vector',
      scheme: 'tms',
      bounds: [
        120.538764953613,
        31.4973964691162,
        121.061668395996,
        31.8380527496338,
      ],
    },
  },
  glyphs:
    'http://36.153.213.20/geoenginev2/csmap/csmap_color/fonts/{fontstack}/{range}.pbf',
  sprite: 'http://36.153.213.20/geoenginev2/csmap/csmap_color/sprites/sprite',
  zoom: 10,
  center: [120.83394, 31.64402],
  layers: [
    {
      id: 'background_color',
      type: 'background',
      paint: {
        'background-color': '#FAFAFA',
      },
    },
    {
      id: 'HY_P_color',
      type: 'fill',
      source: 'QG_BaseMap',
      'source-layer': 'HY_P',
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'XZQ_World_P_color',
      type: 'fill',
      source: 'QG_BaseMap',
      'source-layer': 'XZQ_World_P',
      layout: {},
      paint: {
        'fill-color': '#FFFEFA',
      },
    },
    {
      id: 'XZQ_World_L_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'XZQ_World_P',
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          '#9B9B9B',
          6,
          '#686868',
          15,
          '#5B5B5B',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          1,
          6,
          1.5,
          8,
          2.5,
          12,
          3,
          14,
          4,
          16,
          5,
        ],
      },
    },
    {
      id: 'XZQ_GJ_P_color',
      type: 'fill',
      source: 'QG_BaseMap',
      'source-layer': 'XZQ_GJ_P',
      layout: {},
      paint: {
        'fill-color': '#FFFEFA',
      },
    },
    {
      id: 'SX_P_005_5_color',
      type: 'fill',
      source: 'QG_BaseMap',
      'source-layer': 'SX_P_005',
      minzoom: 12,
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'SX_P_005_4_color',
      type: 'fill',
      source: 'QG_BaseMap',
      'source-layer': 'SX_P_005',
      minzoom: 10,
      maxzoom: 12,
      filter: ['>=', ['to-number', ['get', 'mj']], 5000000],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'SX_P_005_3_color',
      type: 'fill',
      source: 'QG_BaseMap',
      'source-layer': 'SX_P_005',
      minzoom: 8,
      maxzoom: 10,
      filter: ['>=', ['to-number', ['get', 'mj']], 10000000],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'SX_P_005_2_color',
      type: 'fill',
      source: 'QG_BaseMap',
      'source-layer': 'SX_P_005',
      minzoom: 6,
      maxzoom: 8,
      filter: ['>=', ['to-number', ['get', 'mj']], 50000000],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'SX_P_005_1_color',
      type: 'fill',
      source: 'QG_BaseMap',
      'source-layer': 'SX_P_005',
      minzoom: 4,
      maxzoom: 6,
      filter: ['>=', ['to-number', ['get', 'mj']], 200000000],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'XZJX_XJ_L_YS_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'XZJX_XJ_L_YS',
      minzoom: 10,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          7,
          '#C1C1C1',
          9,
          '#B4B4B4',
          14,
          '#8E8E8E',
          18,
          '#686868',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          7,
          0.2,
          9,
          0.5,
          10,
          1,
          12,
          1.2,
          14,
          2,
          16,
          3,
        ],
      },
    },
    {
      id: 'XZJX_City_L_YS_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'XZJX_City_L_YS',
      minzoom: 10,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          6,
          '#B4B4B4',
          9,
          '#8E8E8E',
          15,
          '#686868',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          5,
          0.2,
          6,
          0.5,
          8,
          1.2,
          12,
          2,
          14,
          3,
          16,
          4,
        ],
      },
    },
    {
      id: 'XZJX_SJ_L_YS_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'XZJX_SJ_L_YS',
      minzoom: 10,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          '#B4B4B4',
          6,
          '#8E8E8E',
          12,
          '#686868',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          0.5,
          6,
          1.2,
          8,
          2,
          12,
          3,
          14,
          4,
          16,
          5,
        ],
      },
    },
    {
      id: 'XZJX_GJ_L_YS_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'XZJX_GJ_L_YS',
      minzoom: 10,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#B2a471',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          1,
          6,
          1.5,
          8,
          2.5,
          12,
          3,
          14,
          4,
          16,
          5,
        ],
      },
    },
    {
      id: 'XZJX_XJ_L_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'XZJX_XJ_L',
      minzoom: 7,
      maxzoom: 10,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          7,
          '#C1C1C1',
          9,
          '#B4B4B4',
          14,
          '#8E8E8E',
          18,
          '#686868',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          7,
          0.2,
          9,
          0.5,
          10,
          1,
          12,
          1.2,
          14,
          2,
          16,
          3,
        ],
      },
    },
    {
      id: 'XZJX_City_L_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'XZJX_City_L',
      minzoom: 5,
      maxzoom: 10,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          6,
          '#B4B4B4',
          9,
          '#8E8E8E',
          15,
          '#686868',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          5,
          0.2,
          6,
          0.5,
          8,
          1.2,
          12,
          2,
          14,
          3,
          16,
          4,
        ],
      },
    },
    {
      id: 'XZJX_SJ_L_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'XZJX_SJ_L',
      maxzoom: 10,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          '#B4B4B4',
          6,
          '#8E8E8E',
          12,
          '#686868',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          0.5,
          6,
          1.2,
          8,
          2,
          12,
          3,
          14,
          4,
          16,
          5,
        ],
      },
    },
    {
      id: 'XZJX_GJ_L_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'XZJX_GJ_L',
      maxzoom: 10,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#B2a471',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          1,
          6,
          1.5,
          8,
          2.5,
          12,
          3,
          14,
          4,
          16,
          5,
        ],
      },
    },
    {
      id: 'JT_GL_Case_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'JT_GL_L',
      minzoom: 8,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          '#CC8F62',
          11,
          '#D98D41',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          8,
          3,
          9,
          4,
          10,
          5,
          11,
          7,
          12,
          9,
          14,
          12,
          16,
          14,
        ],
      },
    },
    {
      id: 'JT_GL_L_color',
      type: 'line',
      source: 'QG_BaseMap',
      'source-layer': 'JT_GL_L',
      minzoom: 4,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          '#F0AA65',
          5,
          '#FFA54E',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          4,
          0.5,
          6,
          1,
          8,
          1.5,
          9,
          2,
          10,
          3,
          11,
          5,
          12,
          7,
          14,
          10,
          16,
          12,
        ],
      },
    },
    {
      id: 'JT_GL_SG_color',
      type: 'symbol',
      source: 'QG_BaseMap',
      'source-layer': 'JT_GL_L',
      minzoom: 8,
      filter: ['match', ['get', 'lx'], ['S'], true, false],
      layout: {
        'symbol-placement': 'line',
        'text-font': ['ArialBold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 7, 9, 13, 10],
        'text-field': ['to-string', ['get', 'rn']],
        'text-offset': [0, 0.3],
        'icon-image': [
          'step',
          ['zoom'],
          '',
          8,
          ['match', ['get', 'Len'], ['2'], 'GSGL_S/省道/2', 'GSGL_S/省道/3'],
          13,
          ['match', ['get', 'Len'], ['2'], 'GSGL_L/省道/3', 'GSGL_L/省道/4'],
        ],
        'icon-rotation-alignment': 'viewport',
        'text-rotation-alignment': 'viewport',
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          250,
          10,
          300,
          11,
          400,
          12,
          500,
        ],
      },
      paint: {
        'text-color': '#FFFFFF',
      },
    },
    {
      id: 'JT_GL_GG_color',
      type: 'symbol',
      source: 'QG_BaseMap',
      'source-layer': 'JT_GL_L',
      minzoom: 7,
      filter: ['match', ['get', 'lx'], ['G'], true, false],
      layout: {
        'symbol-placement': 'line',
        'text-font': ['ArialBold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 7, 9, 13, 10],
        'text-field': ['to-string', ['get', 'rn']],
        'text-offset': [0, 0.3],
        'icon-image': [
          'step',
          ['zoom'],
          '',
          7,
          [
            'match',
            ['get', 'Len'],
            ['2'],
            'GSGL_S/国道/2',
            ['3'],
            'GSGL_S/国道/3',
            ['4'],
            'GSGL_S/国道/4',
            'GSGL_S/国道/5',
          ],
          13,
          [
            'match',
            ['get', 'Len'],
            ['2'],
            'GSGL_L/国道/3',
            ['3'],
            'GSGL_L/国道/4',
            ['4'],
            'GSGL_L/国道/5',
            'GSGL_L/国道/6',
          ],
        ],
        'icon-rotation-alignment': 'viewport',
        'text-rotation-alignment': 'viewport',
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          250,
          10,
          300,
          11,
          400,
          12,
          500,
        ],
      },
      paint: {
        'text-color': '#FFFFFF',
      },
    },
    {
      id: 'XZQ_XJ_PT_color',
      type: 'symbol',
      source: 'QG_BaseMap',
      'source-layer': 'XZQ_XJ_PT',
      filter: ['match', ['get', 'bzmc'], ['常熟市'], false, true],
      minzoom: 8,
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          10,
          10,
          12,
          12,
          14,
          14,
          16,
          16,
          18,
        ],
        'text-max-angle': 38,
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          12,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-padding': 2,
        'text-anchor': 'center',
        'text-field': ['to-string', ['get', 'bzmc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          '#818181',
          12,
          '#686868',
        ],
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'XZQ_City_PT_color',
      type: 'symbol',
      source: 'QG_BaseMap',
      'source-layer': 'XZQ_City_PT',
      minzoom: 6,
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          6,
          10,
          8,
          12,
          10,
          14,
          12,
          16,
          16,
          18,
        ],
        'text-max-angle': 38,
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          8,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-padding': 2,
        'text-anchor': 'center',
        'text-field': ['to-string', ['get', 'bzmc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          6,
          '#686868',
          12,
          '#4E4E4E',
        ],
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'XZQ_SJ_PT_color',
      type: 'symbol',
      source: 'QG_BaseMap',
      'source-layer': 'XZQ_SJ_PT',
      minzoom: 3,
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          3,
          9,
          4,
          11,
          6,
          12,
          8,
          14,
          10,
          16,
          12,
          18,
          14,
          20,
          16,
          22,
        ],
        'text-max-angle': 38,
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          5,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-padding': 2,
        'text-anchor': 'center',
        'text-field': ['to-string', ['get', 'bzmc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          4,
          '#686868',
          8,
          '#4E4E4E',
          12,
          '#353535',
        ],
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'xzqh_qxjxzq_p_color',
      type: 'fill',
      source: 'xzqh_qxjxzq_p',
      'source-layer': 'xzqh_qxjxzq_p',
      minzoom: 8,
      layout: {},
      paint: {
        'fill-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          '#FAF8F0',
          22,
          '#F2F0E9',
        ],
      },
    },
    {
      id: 'xzqh_xzjx_l_xz_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'xzqh_xzjx_l',
      filter: ['match', ['get', 'jxlx'], ['乡镇界'], true, false],
      minzoom: 10,
      maxzoom: 15,
      layout: {},
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          '#B2B2B2',
          16,
          '#808080',
          18,
          '#4E4E4E',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          0.5,
          11,
          0.5,
          12,
          1,
          16,
          2,
        ],
        'line-dasharray': [
          'step',
          ['zoom'],
          ['literal', [2, 2]],
          10,
          ['literal', [10, 10]],
          12,
          ['literal', [10, 10]],
        ],
      },
    },
    {
      id: 'xzqh_qxjxzq_b_300_color',
      type: 'fill',
      source: 'xzqh_qxjxzq_b_300',
      'source-layer': 'xzqh_qxjxzq_b_300',
      minzoom: 8,
      layout: {},
      paint: {
        'fill-color': [
          'match',
          ['to-number', ['get', 'distance']],
          [300],
          '#FF9898',
          [600],
          '#FFB2B2',
          '#000000',
        ],
        'fill-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          0.8,
          11,
          0.6,
          12,
          0.4,
        ],
        'fill-outline-color': 'hsla(0, 0%, 0%, 0)',
      },
    },
    {
      id: 'xzqh_qxjxzq_b_300_colorbak_color',
      type: 'fill',
      source: 'xzqh_qxjxzq_b_300',
      'source-layer': 'xzqh_qxjxzq_b_300w',
      minzoom: 8,
      layout: {},
      paint: {
        'fill-color': [
          'match',
          ['to-number', ['get', 'distance']],
          [300],
          '#CCC8C2',
          [600],
          '#E6E1DA',
          '#000000',
        ],
        'fill-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          0.8,
          11,
          0.6,
          12,
          0.4,
        ],
        'fill-outline-color': 'hsla(0, 0%, 0%, 0)',
      },
    },
    {
      id: 'qydy_dk_p_color',
      type: 'fill',
      source: 'CSS_BaseMap',
      'source-layer': 'qydy_dk_p',
      minzoom: 14,
      layout: {},
      paint: {
        'fill-color': [
          'match',
          ['get', 'flmc'],
          ['城镇住宅用地'],
          '#EDEBE2',
          ['教育用地'],
          '#D4DCE2',
          ['医疗卫生用地'],
          '#E6D9D8',
          ['体育用地', '文化设施用地'],
          '#D9DFD0',
          ['商务金融用地', '零售商业用地', '其他商服用地'],
          '#F2ECDE',
          ['风景名胜设施用地', '公园与绿地'],
          '#A0D097',
          '#DBDBDB',
        ],
        'fill-opacity': [
          'case',
          [
            'match',
            ['get', 'flmc'],
            ['风景名胜设施用地', '公园与绿地'],
            true,
            false,
          ],
          1,
          [
            'match',
            ['get', 'flmc'],
            [
              '城镇住宅用地',
              '教育用地',
              '医疗卫生用地',
              '体育用地',
              '文化设施用地',
            ],
            true,
            false,
          ],
          1,
          [
            'match',
            ['get', 'flmc'],
            ['商务金融用地', '零售商业用地', '其他商服用地'],
            true,
            false,
          ],
          0.7,
          ['match', ['get', 'flmc'], ['工业用地'], true, false],
          0.3,
          0.3,
        ],
        'fill-outline-color': 'hsla(0, 0%, 0%, 0)',
      },
    },
    {
      id: 'ld_ld_p_nb_color',
      type: 'fill',
      source: 'ld_ld_p_nb',
      'source-layer': 'ld_ld_p_nb',
      minzoom: 16,
      layout: {},
      paint: {
        'fill-color': [
          'match',
          ['get', 'dkflmc'],
          ['城镇住宅用地'],
          '#E3E1D8',
          ['教育用地'],
          '#CBD5DC',
          ['医疗卫生用地'],
          '#E2D4D2',
          ['体育用地', '文化设施用地'],
          '#D2D8C8',
          ['商务金融用地', '零售商业用地', '其他商服用地'],
          '#CCD4C1',
          ['风景名胜设施用地', '公园与绿地'],
          '#A0D097',
          '#D9D9D9',
        ],
        'fill-opacity': [
          'match',
          ['get', 'Type'],
          [
            '城镇住宅用地',
            '教育用地',
            '医疗卫生用地',
            '体育用地',
            '文化设施用地',
            '商务金融用地',
            '零售商业用地',
            '其他商服用地',
            '风景名胜设施用地',
            '公园与绿地',
          ],
          1,
          0.6,
        ],
      },
    },
    {
      id: 'ld_gy_p_10_color',
      type: 'fill',
      source: 'ld_gy_p',
      'source-layer': 'ld_gy_p',
      filter: ['>=', ['to-number', ['get', 'mj']], 100000],
      minzoom: 10,
      maxzoom: 11,
      layout: {},
      paint: {
        'fill-color': '#A0D097',
      },
    },
    {
      id: 'ld_gy_p_color',
      type: 'fill',
      source: 'ld_gy_p',
      'source-layer': 'ld_gy_p',
      minzoom: 11,
      layout: {},
      paint: {
        'fill-color': '#A0D097',
      },
    },
    {
      id: 'ld_ld_p_fnb_11_color',
      type: 'fill',
      source: 'ld_ld_p_fnb',
      'source-layer': 'ld_ld_p_fnb',
      filter: ['>=', ['to-number', ['get', 'mj']], 50000],
      minzoom: 11,
      maxzoom: 12,
      layout: {},
      paint: {
        'fill-color': '#A0D097',
      },
    },
    {
      id: 'ld_ld_p_fnb_12_color',
      type: 'fill',
      source: 'ld_ld_p_fnb',
      'source-layer': 'ld_ld_p_fnb',
      filter: ['>=', ['to-number', ['get', 'mj']], 20000],
      minzoom: 12,
      maxzoom: 13,
      layout: {},
      paint: {
        'fill-color': '#A0D097',
      },
    },
    {
      id: 'ld_ld_p_fnb_13_color',
      type: 'fill',
      source: 'ld_ld_p_fnb',
      'source-layer': 'ld_ld_p_fnb',
      filter: ['>=', ['to-number', ['get', 'mj']], 10000],
      minzoom: 12,
      maxzoom: 13,
      layout: {},
      paint: {
        'fill-color': '#A0D097',
      },
    },

    {
      id: 'sx_sx_p_hp_10_color',
      type: 'fill',
      source: 'sx_sx_p',
      'source-layer': 'sx_sx_p',
      minzoom: 10,
      maxzoom: 11,
      filter: [
        'all',
        ['match', ['get', 'lx'], ['湖泊'], true, false],
        ['>=', ['to-number', ['get', 'mj']], 5000000],
      ],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'sx_sx_p_hp_11_color',
      type: 'fill',
      source: 'sx_sx_p',
      'source-layer': 'sx_sx_p',
      minzoom: 11,
      filter: ['match', ['get', 'lx'], ['湖泊'], true, false],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'sx_sx_p_hl_10_color',
      type: 'fill',
      source: 'sx_sx_p',
      'source-layer': 'sx_sx_p',
      minzoom: 10,
      maxzoom: 11,
      filter: [
        'all',
        ['match', ['get', 'lx'], ['河流'], true, false],
        ['>=', ['to-number', ['get', 'mj']], 600000],
      ],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'sx_sx_p_hl_11_color',
      type: 'fill',
      source: 'sx_sx_p',
      'source-layer': 'sx_sx_p',
      minzoom: 11,
      maxzoom: 12,
      filter: [
        'all',
        ['match', ['get', 'lx'], ['河流'], true, false],
        ['>=', ['to-number', ['get', 'mj']], 200000],
      ],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'sx_sx_p_hl_12_color',
      type: 'fill',
      source: 'sx_sx_p',
      'source-layer': 'sx_sx_p',
      minzoom: 12,
      maxzoom: 13,
      filter: [
        'all',
        ['match', ['get', 'lx'], ['河流'], true, false],
        ['>=', ['to-number', ['get', 'mj']], 150000],
      ],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'sx_sx_p_hl_13_color',
      type: 'fill',
      source: 'sx_sx_p',
      'source-layer': 'sx_sx_p',
      minzoom: 13,
      maxzoom: 14,
      filter: [
        'all',
        ['match', ['get', 'lx'], ['河流'], true, false],
        ['>=', ['to-number', ['get', 'mj']], 100000],
      ],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'sx_sx_p_hl_14_color',
      type: 'fill',
      source: 'sx_sx_p',
      'source-layer': 'sx_sx_p',
      minzoom: 14,
      filter: [
        'all',
        ['match', ['get', 'lx'], ['河流'], true, false],
        ['>=', ['to-number', ['get', 'mj']], 0],
      ],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'sx_sx_p_qt_14_color',
      type: 'fill',
      source: 'sx_sx_p',
      'source-layer': 'sx_sx_p',
      minzoom: 14,
      maxzoom: 15,
      filter: [
        'all',
        ['match', ['get', 'lx'], ['湖泊', '河流'], false, true],
        ['>=', ['to-number', ['get', 'mj']], 100000],
      ],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'sx_sx_p_qt_15_color',
      type: 'fill',
      source: 'sx_sx_p',
      'source-layer': 'sx_sx_p',
      minzoom: 15,
      maxzoom: 16,
      filter: [
        'all',
        ['match', ['get', 'lx'], ['湖泊', '河流'], false, true],
        ['>=', ['to-number', ['get', 'mj']], 50000],
      ],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'sx_sx_p_qt_16_color',
      type: 'fill',
      source: 'sx_sx_p',
      'source-layer': 'sx_sx_p',
      minzoom: 16,
      filter: [
        'all',
        ['match', ['get', 'lx'], ['湖泊', '河流'], false, true],
        ['>=', ['to-number', ['get', 'mj']], 0],
      ],
      layout: {},
      paint: {
        'fill-color': '#9DBAD1',
      },
    },
    {
      id: 'DLJT_CSDL_L_NBDL_Case_S_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['内部道路'], true, false],
      minzoom: 13,
      maxzoom: 14,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#d9d9d9',
        'line-width': 0.5,
      },
    },
    {
      id: 'DLJT_XCDL_L_Case_S_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_xcdl_lS',
      minzoom: 11,
      maxzoom: 12,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#d9d9d9',
        'line-width': 0.5,
      },
    },
    {
      id: 'DLJT_CSDL_L_ZL_Case_S_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['支路'], true, false],
      minzoom: 11,
      maxzoom: 12,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#d9d9d9',
        'line-width': 0.5,
      },
    },
    {
      id: 'DLJT_GL_L_XD_S_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: ['match', ['get', 'lx'], ['县道'], true, false],
      minzoom: 10,
      maxzoom: 11,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#d9d9d9',
        'line-width': 0.5,
      },
    },

    {
      id: 'DLJT_GL_L_CGD_S_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['次干道'], true, false],
      minzoom: 10,
      maxzoom: 11,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#d9d9d9',
        'line-width': 0.1,
      },
    },
    {
      id: 'DLJT_GL_L_GSD_S_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: [
        'all',
        ['match', ['get', 'jsdj'], ['高速公路'], false, true],
        ['match', ['get', 'lx'], ['国道', '省道'], true, false],
      ],
      minzoom: 8,
      maxzoom: 9,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#d9d9d9',
        'line-width': 0.5,
      },
    },
    {
      id: 'DLJT_YL_L_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_yl_l',
      filter: ['match', ['get', 'lx'], ['匝道'], false, true],
      minzoom: 13,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'match',
          ['get', 'lx'],
          ['快速路'],
          '#d3ae47',
          ['主干道'],
          '#D9D7B8',
          ['国道'],
          '#d9c37c',
          ['省道'],
          '#d9c37c',
          ['次干道'],
          '#D9D9D9',
          ['县道'],
          '#D9D9D9',
          '#D9D9D9',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          [
            'match',
            ['get', 'lx'],
            ['快速路'],
            4,
            ['主干道'],
            4,
            ['国道'],
            4,
            ['省道'],
            4,
            ['次干道'],
            2,
            ['县道'],
            2,
            ['支路'],
            0,
            1,
          ],
          14,
          [
            'match',
            ['get', 'lx'],
            ['快速路'],
            6,
            ['主干道'],
            6,
            ['国道'],
            6,
            ['省道'],
            6,
            ['次干道'],
            4,
            ['县道'],
            4,
            ['支路'],
            2,
            1,
          ],
          18,
          [
            'match',
            ['get', 'lx'],
            ['快速路'],
            10,
            ['主干道'],
            10,
            ['国道'],
            10,
            ['省道'],
            10,
            ['次干道'],
            8,
            ['县道'],
            8,
            ['支路'],
            6,
            1,
          ],
        ],
      },
    },
    {
      id: 'DLJT_CSDL_L_NBDL_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['内部道路'], true, false],
      minzoom: 14,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#D9D9D9',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          14,
          3,
          16,
          5,
          18,
          7,
        ],
      },
    },
    {
      id: 'DLJT_XCDL_L_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_xcdl_l',
      minzoom: 12,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#D9D9D9',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          12,
          3,
          14,
          6,
          16,
          8,
          18,
          10,
        ],
      },
    },
    {
      id: 'DLJT_GL_L_XID_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: ['match', ['get', 'lx'], ['乡道'], true, false],
      minzoom: 11,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#D9D9D9',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          11,
          3,
          12,
          3,
          14,
          6,
          16,
          8,
          18,
          10,
        ],
      },
    },

    {
      id: 'DLJT_CSDL_L_ZL_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['支路'], true, false],
      minzoom: 12,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#D9D9D9',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          11,
          3,
          12,
          3,
          14,
          6,
          16,
          8,
          18,
          10,
        ],
      },
    },
    {
      id: 'DLJT_GL_L_XD_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: ['match', ['get', 'lx'], ['县道'], true, false],
      minzoom: 11,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#D9D9D9',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          11,
          5,
          12,
          5,
          14,
          8,
          16,
          10,
          18,
          12,
        ],
      },
    },
    {
      id: 'DLJT_CSDL_L_CGD_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['次干道'], true, false],
      minzoom: 11,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#D9D9D9',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          11,
          3,
          12,
          5,
          14,
          8,
          16,
          10,
          18,
          12,
        ],
      },
    },
    {
      id: 'DLJT_CSDL_L_ZGD_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['主干道'], true, false],
      minzoom: 10,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          '#CCCAAD',
          12,
          '#D9D7B8',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          10,
          3,
          11,
          5,
          12,
          7,
          14,
          10,
          16,
          12,
          18,
          14,
        ],
      },
    },

    {
      id: 'DLJT_GL_L_SD_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: [
        'all',
        ['match', ['get', 'jsdj'], ['高速公路'], false, true],
        ['match', ['get', 'lx'], ['省道'], true, false],
      ],
      minzoom: 9,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          9,
          '#cdb673',
          11,
          '#d9c37c',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          8,
          1.5,
          9,
          3,
          10,
          5,
          12,
          7,
          14,
          10,
          16,
          12,
          18,
          14,
        ],
      },
    },
    {
      id: 'DLJT_GL_L_GD_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: [
        'all',
        ['match', ['get', 'jsdj'], ['高速公路'], false, true],
        ['match', ['get', 'lx'], ['国道'], true, false],
      ],
      minzoom: 9,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          9,
          '#cdb673',
          11,
          '#d9c37c',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          8,
          1.5,
          9,
          3,
          10,
          5,
          12,
          7,
          14,
          10,
          16,
          12,
          18,
          14,
        ],
      },
    },
    {
      id: 'DLJT_QL_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_ql_l',
      minzoom: 13,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#D9D9D9',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          8,
          3,
          9,
          5,
          10,
          7,
          12,
          3,
          14,
          5,
          18,
          7,
        ],
      },
    },
    {
      id: 'DLJT_ZD_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_yl_l',
      filter: ['match', ['get', 'lx'], ['匝道'], true, false],
      minzoom: 13,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          '#CC8F62',
          11,
          '#D98D41',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          8,
          3,
          9,
          5,
          10,
          7,
          12,
          3,
          14,
          5,
          18,
          7,
        ],
      },
    },
    {
      id: 'DLJT_GL_L_GSGL_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: ['match', ['get', 'jsdj'], ['高速公路'], true, false],
      minzoom: 8,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          '#CC8F62',
          11,
          '#D98D41',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          8,
          3,
          9,
          4,
          10,
          5,
          11,
          7,
          12,
          9,
          14,
          12,
          16,
          14,
        ],
      },
    },
    {
      id: 'DLJT_YL_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_yl_l',
      filter: ['match', ['get', 'lx'], ['匝道'], false, true],
      minzoom: 13,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'match',
          ['get', 'lx'],
          ['快速路'],
          '#ffd050',
          ['主干道'],
          '#FFFCCB',
          ['国道'],
          '#ffeb93',
          ['省道'],
          '#ffeb93',
          ['次干道'],
          '#FFFFFF',
          ['县道'],
          '#FFFFFF',
          '#FFFFFF',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          [
            'match',
            ['get', 'lx'],
            ['快速路'],
            2,
            ['主干道'],
            2,
            ['国道'],
            2,
            ['省道'],
            2,
            ['次干道'],
            1,
            ['县道'],
            1,
            ['支路'],
            0,
            1,
          ],
          14,
          [
            'match',
            ['get', 'lx'],
            ['快速路'],
            4,
            ['主干道'],
            4,
            ['国道'],
            4,
            ['省道'],
            4,
            ['次干道'],
            2,
            ['县道'],
            2,
            ['支路'],
            1,
            1,
          ],
          18,
          [
            'match',
            ['get', 'lx'],
            ['快速路'],
            8,
            ['主干道'],
            8,
            ['国道'],
            8,
            ['省道'],
            8,
            ['次干道'],
            6,
            ['县道'],
            6,
            ['支路'],
            4,
            1,
          ],
        ],
      },
    },
    {
      id: 'DLJT_CSDL_L_NBDL_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['内部道路'], true, false],
      minzoom: 14,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': '#FFFFFF',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          14,
          2,
          16,
          3,
          18,
          5,
        ],
      },
    },
    {
      id: 'DLJT_XCDL_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_xcdl_l',
      minzoom: 12,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#FFFFFF',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          12,
          2,
          14,
          4,
          16,
          6,
          18,
          8,
        ],
      },
    },
    {
      id: 'DLJT_GL_L_XID_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: ['match', ['get', 'lx'], ['乡道'], true, false],
      minzoom: 11,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#FFFFFF',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          11,
          2,
          12,
          2,
          14,
          4,
          16,
          6,
          18,
          8,
        ],
      },
    },
    {
      id: 'DLJT_GL_L_XD_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: ['match', ['get', 'lx'], ['县道'], true, false],
      minzoom: 11,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#FFFFFF',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          11,
          3,
          12,
          3,
          14,
          6,
          16,
          8,
          18,
          10,
        ],
      },
    },
    {
      id: 'DLJT_CSDL_L_ZL_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      minzoom: 12,
      filter: ['match', ['get', 'lx'], ['支路'], true, false],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#FFFFFF',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          12,
          2,
          14,
          4,
          16,
          6,
          18,
          8,
        ],
      },
    },
    {
      id: 'DLJT_CSDL_L_CGD_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      minzoom: 11,
      filter: ['match', ['get', 'lx'], ['次干道'], true, false],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#FFFFFF',
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          11,
          1.5,
          12,
          3,
          14,
          6,
          16,
          8,
          18,
          10,
        ],
      },
    },
    {
      id: 'DLJT_CSDL_L_ZGD_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      minzoom: 10,
      filter: ['match', ['get', 'lx'], ['主干道'], true, false],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          '#FEFBCB',
          12,
          '#FFFCCB',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          10,
          2,
          11,
          3.5,
          12,
          5,
          14,
          8,
          16,
          10,
          18,
          12,
        ],
      },
    },

    {
      id: 'DLJT_GL_L_SD_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      minzoom: 9,
      filter: [
        'all',
        ['match', ['get', 'jsdj'], ['高速公路'], false, true],
        ['match', ['get', 'lx'], ['省道'], true, false],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          9,
          '#ffe690',
          11,
          '#ffeb93',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          9,
          2,
          10,
          3,
          12,
          5,
          14,
          8,
          16,
          10,
          18,
          12,
        ],
      },
    },
    {
      id: 'DLJT_GL_L_GD_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: [
        'all',
        ['match', ['get', 'jsdj'], ['高速公路'], false, true],
        ['match', ['get', 'lx'], ['国道'], true, false],
      ],
      minzoom: 9,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          9,
          '#ffe690',
          11,
          '#ffeb93',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          9,
          2,
          10,
          3,
          12,
          5,
          14,
          8,
          16,
          10,
          18,
          12,
        ],
      },
    },
    {
      id: 'DLJT_ZD_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_yl_l',
      filter: ['match', ['get', 'lx'], ['匝道'], true, false],
      minzoom: 13,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          '#F0AA65',
          11,
          '#FFA54E',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          8,
          1.5,
          9,
          3,
          10,
          5,
          12,
          1.5,
          14,
          3,
          18,
          5,
        ],
      },
    },
    {
      id: 'DLJT_GL_L_GSGL_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: ['match', ['get', 'jsdj'], ['高速公路'], true, false],
      minzoom: 8,
      layout: {
        'line-cap': 'round',
        'line-join': 'round',
      },
      paint: {
        'line-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          '#F0AA65',
          11,
          '#FFA54E',
        ],
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          4,
          0.5,
          6,
          1,
          8,
          1.5,
          9,
          2,
          10,
          3,
          11,
          5,
          12,
          7,
          14,
          10,
          16,
          12,
        ],
      },
    },
    {
      id: 'GDJT_Tlx_L_Case_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'gdjt_tlx_l',
      minzoom: 11,
      layout: {},
      paint: {
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          10,
          2,
          11,
          2,
          12,
          2.4,
          14,
          3,
          18,
          4,
        ],
        'line-color': '#7B86AD',
      },
    },
    {
      id: 'GDJT_Tlx_L_color',
      type: 'line',
      source: 'CSS_BaseMap',
      'source-layer': 'gdjt_tlx_l',
      minzoom: 11,
      layout: {},
      paint: {
        'line-width': [
          'interpolate',
          ['linear'],
          ['zoom'],
          0,
          0,
          10,
          1,
          11,
          1,
          12,
          2,
          14,
          2.6,
          18,
          3.6,
        ],
        'line-color': '#FFFFFF',
        'line-dasharray': [
          'step',
          ['zoom'],
          ['literal', [4, 4]],
          10,
          ['literal', [8, 8]],
          11,
          ['literal', [10, 10]],
          12,
          ['literal', [8, 8]],
        ],
      },
    },
    {
      id: 'jgzw_jzw_p_cs_color',
      type: 'fill-extrusion',
      source: 'jgzw_jzw_p',
      'source-layer': 'jgzw_jzw_p',
      minzoom: 16,
      layout: {},
      paint: {
        'fill-extrusion-height': ['to-number', ['get', 'jzwgd']],
        'fill-extrusion-color': '#FFFFFF',
        'fill-extrusion-opacity': [
          'interpolate',
          ['linear'],
          ['zoom'],
          15,
          0.25,
          18,
          0.5,
        ],
        'fill-extrusion-vertical-gradient': false,
      },
    },
    {
      id: 'sx_sx_pt_10_color',
      type: 'symbol',
      source: 'sx_sx_pt',
      'source-layer': 'sx_sx_pt',
      minzoom: 10,
      maxzoom: 11,
      filter: [
        'all',
        ['match', ['get', 'lx'], ['湖泊'], true, false],
        ['>=', ['to-number', ['get', 'mj']], 5000000],
      ],
      layout: {
        'text-line-height': 1.1,
        'text-size': ['interpolate', ['linear'], ['zoom'], 8, 9, 10, 10],
        'text-max-angle': 38,
        'text-font': ['MicrosoftYaHeiRegular'],
        'text-padding': 2,
        'text-anchor': 'center',
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': '#3F5C73',
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },
    {
      id: 'sx_sx_pt_color',
      type: 'symbol',
      source: 'sx_sx_pt',
      'source-layer': 'sx_sx_pt',
      minzoom: 11,
      filter: ['match', ['get', 'lx'], ['湖泊'], true, false],
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          9,
          10,
          10,
          12,
          11,
          14,
          12,
        ],
        'text-max-angle': 38,
        'text-font': ['MicrosoftYaHeiRegular'],
        'text-padding': 2,
        'text-anchor': 'center',
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': '#3F5C73',
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },
    {
      id: 'qydy_dk_pt_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'qydy_dk_pt',
      filter: ['match', ['get', 'mc'], ['无'], false, true],
      minzoom: 14,
      layout: {
        'text-field': ['to-string', ['get', 'mc']],
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          17,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-size': ['interpolate', ['linear'], ['zoom'], 14, 10, 18, 12],
        'text-padding': ['interpolate', ['linear'], ['zoom'], 14, 20, 16, 2],
      },
      paint: {
        'text-color': [
          'match',
          ['get', 'flmc'],
          ['城镇住宅用地'],
          '#5D4E3A',
          ['教育用地'],
          '#455D73',
          ['医疗卫生用地'],
          '#6E394B',
          ['体育用地', '文化设施用地'],
          '#888C81',
          ['商务金融用地', '零售商业用地', '其他商服用地'],
          '#726850',
          '#686868',
        ],
        'text-halo-width': 0,
        'text-halo-color': '#FFFFFF',
      },
    },

    {
      id: 'DLJT_XCDL_L_Label_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_xcdl_l',
      minzoom: 12,
      layout: {
        'symbol-placement': 'line',
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          18,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          9,
          14,
          10,
          18,
          12,
        ],
        'text-max-width': 8,
        'text-field': ['to-string', ['get', 'jc']],
        'text-letter-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          0.1,
          13,
          0.2,
          14,
          0.2,
          16,
          0.3,
        ],
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          0,
          12,
          500,
          13,
          500,
          16,
          900,
        ],
        'text-optional': true,
      },
      paint: {
        'text-color': '#4E4E4E',
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },
    {
      id: 'DLJT_GL_L_XID_Label_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: ['match', ['get', 'lx'], ['乡道'], true, false],
      minzoom: 12,
      layout: {
        'symbol-placement': 'line',
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          18,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          9,
          14,
          10,
          18,
          12,
        ],
        'text-max-width': 8,
        'text-field': ['to-string', ['get', 'jc']],
        'text-letter-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          0.1,
          13,
          0.2,
          14,
          0.2,
          16,
          0.3,
        ],
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          0,
          12,
          600,
          13,
          500,
          16,
          900,
        ],
        'text-optional': true,
      },
      paint: {
        'text-color': '#4E4E4E',
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },
    {
      id: 'DLJT_CSDL_L_ZL_Label_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['支路'], true, false],
      minzoom: 12,
      layout: {
        'symbol-placement': 'line',
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          18,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          9,
          14,
          10,
          18,
          12,
        ],
        'text-max-width': 8,
        'text-field': ['to-string', ['get', 'jc']],
        'text-letter-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          0.1,
          13,
          0.2,
          14,
          0.2,
          16,
          0.3,
        ],
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          0,
          12,
          600,
          13,
          500,
          16,
          900,
        ],
        'text-optional': true,
      },
      paint: {
        'text-color': '#4E4E4E',
        'text-halo-color': '#fff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'DLJT_GL_L_XD_Label_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: ['match', ['get', 'lx'], ['县道'], true, false],
      minzoom: 11,
      layout: {
        'symbol-placement': 'line',
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          16,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          9,
          12,
          10,
          16,
          12,
          18,
          14,
        ],
        'text-max-width': 8,
        'text-field': ['to-string', ['get', 'jc']],
        'text-letter-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          0.2,
          11,
          0.1,
          12,
          0.1,
          13,
          0.2,
          14,
          0.2,
          16,
          0.3,
        ],
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          0,
          10,
          250,
          11,
          500,
          12,
          350,
          13,
          550,
          14,
          750,
          16,
          900,
        ],
        'text-optional': true,
      },
      paint: {
        'text-color': '#4E4E4E',
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },
    {
      id: 'DLJT_CSDL_L_CGD_Label_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['次干道'], true, false],
      minzoom: 12,
      layout: {
        'symbol-placement': 'line',
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          16,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          10,
          16,
          12,
          18,
          14,
        ],
        'text-max-width': 8,
        'text-field': ['to-string', ['get', 'jc']],
        'text-letter-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          0.2,
          11,
          0.1,
          12,
          0.1,
          13,
          0.2,
          14,
          0.2,
          16,
          0.3,
        ],
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          0,
          10,
          250,
          11,
          500,
          12,
          500,
          13,
          550,
          14,
          750,
          16,
          900,
        ],
        'text-optional': true,
      },
      paint: {
        'text-color': '#4E4E4E',
        'text-halo-color': '#fff',
        'text-halo-width': 1,
      },
    },
    {
      id: 'DLJT_CSDL_L_ZGD_Label_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_csdl_l',
      filter: ['match', ['get', 'lx'], ['主干道'], true, false],
      minzoom: 11,
      layout: {
        'symbol-placement': 'line',
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          16,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          9,
          12,
          11,
          14,
          12,
          18,
          14,
        ],
        'text-max-width': 8,
        'text-field': ['to-string', ['get', 'jc']],
        'text-letter-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          0.2,
          11,
          0.1,
          12,
          0.1,
          13,
          0.2,
          14,
          0.2,
          16,
          0.3,
        ],
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          0,
          10,
          250,
          11,
          500,
          12,
          500,
          13,
          550,
          14,
          750,
          16,
          900,
        ],
        'text-optional': true,
      },
      paint: {
        'text-color': '#4E4E4E',
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },

    {
      id: 'DLJT_GL_L_GSD_Label_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: [
        'all',
        ['match', ['get', 'jsdj'], ['高速公路'], false, true],
        ['match', ['get', 'lx'], ['国道', '省道'], true, false],
      ],
      minzoom: 10,
      layout: {
        'symbol-placement': 'line',
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          16,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          10,
          12,
          12,
          14,
          12,
          18,
          14,
        ],
        'text-max-width': 8,
        'text-field': ['to-string', ['get', 'jc']],
        'text-letter-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          0.2,
          11,
          0.1,
          12,
          0.1,
          13,
          0.2,
          14,
          0.2,
          16,
          0.3,
        ],
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          0,
          10,
          250,
          11,
          300,
          12,
          350,
          13,
          550,
          14,
          750,
        ],
        'text-optional': true,
      },
      paint: {
        'text-color': '#4E4E4E',
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },
    {
      id: 'DLJT_GL_L_GSGL_Label_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      filter: ['match', ['get', 'jsdj'], ['高速公路'], true, false],
      minzoom: 8,
      layout: {
        'symbol-placement': 'line',
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          15,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          10,
          10,
          12,
          14,
          14,
          18,
          16,
        ],
        'text-max-width': 8,
        'text-field': ['to-string', ['get', 'jc']],
        'text-letter-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          0.2,
          11,
          0.1,
          12,
          0.1,
          13,
          0.2,
          14,
          0.2,
          16,
          0.3,
        ],
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          0,
          10,
          0,
          11,
          300,
          12,
          350,
          13,
          550,
          14,
          750,
        ],
        'text-optional': true,
      },
      paint: {
        'text-color': '#8C4600',
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },

    {
      id: 'DLJT_GL_L_SD_bh_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      minzoom: 10,
      filter: [
        'all',
        ['match', ['get', 'jsdj'], ['高速公路'], false, true],
        ['match', ['get', 'lx'], ['省道'], true, false],
      ],
      layout: {
        'symbol-placement': 'line',
        'text-font': ['ArialBold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 10, 8, 12, 9, 14, 9],
        'text-field': ['to-string', ['get', 'bh']],
        'text-offset': [0, 0.2],
        'icon-image': ['step', ['zoom'], '', 10, 'SD/省道/3', 12, 'SD/省道/4'],
        'icon-rotation-alignment': 'viewport',
        'text-rotation-alignment': 'viewport',
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          0,
          10,
          500,
          11,
          500,
          12,
          350,
          13,
          550,
          14,
          750,
          16,
          900,
        ],
      },
      paint: {
        'text-color': '#4e4e4e',
      },
    },
    {
      id: 'DLJT_GL_L_GD_bh_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      minzoom: 10,
      filter: [
        'all',
        ['match', ['get', 'jsdj'], ['高速公路'], false, true],
        ['match', ['get', 'lx'], ['国道'], true, false],
      ],
      layout: {
        'symbol-placement': 'line',
        'text-font': ['ArialBold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 10, 8, 12, 9, 14, 9],
        'text-field': ['to-string', ['get', 'bh']],
        'text-offset': [0, 0.2],
        'icon-image': ['step', ['zoom'], '', 10, 'SD/省道/3', 12, 'SD/省道/4'],
        'icon-rotation-alignment': 'viewport',
        'text-rotation-alignment': 'viewport',
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          0,
          10,
          500,
          11,
          500,
          12,
          1000,
          13,
          550,
          14,
          750,
          16,
          900,
        ],
      },
      paint: {
        'text-color': '#4e4e4e',
      },
    },

    {
      id: 'DLJT_GL_L_SG_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      minzoom: 10,
      filter: [
        'all',
        ['match', ['get', 'jsdj'], ['高速公路'], true, false],
        ['match', ['get', 'lx'], ['省道'], true, false],
      ],
      layout: {
        'symbol-placement': 'line',
        'text-font': ['ArialBold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 8, 9, 13, 10],
        'text-field': ['to-string', ['get', 'bh']],
        'text-offset': [0, 0.3],
        'icon-image': [
          'step',
          ['zoom'],
          '',
          8,
          [
            'match',
            ['get', 'bh'],
            ['S9', 'S5'],
            'GSGL_S/省道/2',
            'GSGL_S/省道/3',
          ],
          13,
          [
            'match',
            ['get', 'bh'],
            ['S9', 'S5'],
            'GSGL_L/省道/3',
            'GSGL_L/省道/4',
          ],
        ],
        'icon-rotation-alignment': 'viewport',
        'text-rotation-alignment': 'viewport',
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          250,
          10,
          400,
          11,
          400,
          12,
          1000,
        ],
      },
      paint: {
        'text-color': '#FFFFFF',
      },
    },
    {
      id: 'DLJT_GL_L_GG_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_gl_l',
      minzoom: 10,
      filter: [
        'all',
        ['match', ['get', 'jsdj'], ['高速公路'], true, false],
        ['match', ['get', 'lx'], ['国道'], true, false],
      ],
      layout: {
        'symbol-placement': 'line',
        'text-font': ['ArialBold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 8, 9, 13, 10],
        'text-field': ['to-string', ['get', 'bh']],
        'text-offset': [0, 0.3],
        'icon-image': [
          'step',
          ['zoom'],
          '',
          8,
          [
            'match',
            ['get', 'bh'],
            ['G2'],
            'GSGL_S/国道/2',
            ['G50', 'G15'],
            'GSGL_S/国道/3',
            ['G15W'],
            'GSGL_S/国道/5',
            'GSGL_S/国道/6',
          ],
          13,
          [
            'match',
            ['get', 'bh'],
            ['G2'],
            'GSGL_L/国道/3',
            ['G50', 'G15'],
            'GSGL_L/国道/4',
            ['G15W'],
            'GSGL_L/国道/6',
            'GSGL_L/国道/7',
          ],
        ],
        'icon-rotation-alignment': 'viewport',
        'text-rotation-alignment': 'viewport',
        'symbol-spacing': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          250,
          10,
          400,
          11,
          400,
          12,
          1000,
        ],
      },
      paint: {
        'text-color': '#FFFFFF',
      },
    },
    {
      id: 'xqd_poi_pt_color',
      type: 'symbol',
      source: 'xqd_poi_pt',
      'source-layer': 'xqd_poi_pt',
      minzoom: 15,
      layout: {
        'text-line-height': 1.1,
        'text-size': ['interpolate', ['linear'], ['zoom'], 13, 11, 16, 12],
        'icon-image': [
          'match',
          ['get', 'flmc'],
          [
            '科教文化',
            '科教文化_科教文化场馆',
            '科教文化_科研机构',
            '科教文化_培训机构_职业技能培训',
            '科教文化_文化传媒',
            '科教文化_学校_幼儿园',
          ],
          'XX',
          [
            '卫生社保',
            '卫生社保_疾病预防控制机构_卫生防疫站',
            '卫生社保_社会福利保障机构',
            '卫生社保_社区卫生服务中心',
            '卫生社保_专科医院',
          ],
          'YY',
          ['旅游景点', '旅游景点_公园广场_公园', '旅游景点_公园广场_城市广场'],
          'MSGJJD',
          ['房产园区与仓储_商业地产', '房产园区与仓储_商业地产_商住两用楼'],
          'DS',
          '',
        ],
        'text-max-angle': 38,
        'text-font': ['MicrosoftYaHeiRegular'],
        'text-padding': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          30,
          14,
          10,
          16,
          2,
        ],
        'text-offset': [0, 0.5],
        'text-anchor': 'top',
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': [
          'match',
          ['get', 'flmc'],
          [
            '科教文化',
            '科教文化_科教文化场馆',
            '科教文化_科研机构',
            '科教文化_培训机构_职业技能培训',
            '科教文化_文化传媒',
            '科教文化_学校_幼儿园',
          ],
          '#455C72',
          [
            '卫生社保',
            '卫生社保_疾病预防控制机构_卫生防疫站',
            '卫生社保_社会福利保障机构',
            '卫生社保_社区卫生服务中心',
            '卫生社保_专科医院',
          ],
          '#875064',
          ['旅游景点', '旅游景点_公园广场_公园', '旅游景点_公园广场_城市广场'],
          '#4C664C',
          '#343434',
        ],
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },
    {
      id: 'gdjt_tlzd_pt_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'gdjt_tlzd_pt',
      minzoom: 11,
      layout: {
        'text-line-height': 1.1,
        'text-size': ['interpolate', ['linear'], ['zoom'], 13, 11, 16, 12],
        'icon-image': 'HCZ',
        'text-max-angle': 38,
        'text-font': ['MicrosoftYaHeiRegular'],
        'text-padding': 2,
        'text-offset': [0, 0.6],
        'text-anchor': 'top',
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': '#4B6C8D',
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },
    {
      id: 'dljt_qcz_pt_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'dljt_qcz_pt',
      minzoom: 11,
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          10,
          13,
          11,
          16,
          12,
        ],
        'icon-image': 'QCZ',
        'text-max-angle': 38,
        'text-font': ['MicrosoftYaHeiRegular'],
        'text-padding': 2,
        'text-offset': [0, 0.6],
        'text-anchor': 'top',
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': '#4B6C8D',
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1.2,
      },
    },

    {
      id: 'xzqh_zrc_pt_color',
      type: 'symbol',
      source: 'xzqh_zrc_pt',
      'source-layer': 'xzqh_zrc_pt',
      minzoom: 15,
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          14,
          9,
          16,
          11,
          22,
          14,
        ],
        'text-max-angle': 38,
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          18,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-padding': 2,
        'text-anchor': 'center',
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          '#808080',
          16,
          '#4E4E4E',
        ],
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1,
      },
    },
    {
      id: 'xzqh_cjxzq_pt_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'xzqh_xzjg_pt',
      filter: ['match', ['get', 'jb'], ['村级'], true, false],
      minzoom: 14,
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          9,
          14,
          11,
          20,
          14,
        ],
        'text-max-angle': 38,
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          16,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-padding': 2,
        'text-anchor': 'center',
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          '#676767',
          14,
          '#4E4E4E',
        ],
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1.2,
      },
    },

    {
      id: 'xzqh_xzjg_xz_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'xzqh_xzjg_pt',
      filter: ['match', ['get', 'jb'], ['乡镇级'], true, false],
      minzoom: 11,
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          11,
          10,
          14,
          12,
          20,
          14,
        ],
        'text-max-angle': 38,
        'icon-image': [
          'step',
          ['zoom'],
          '',
          11,
          'XZQH_XZ_PT_S',
          16,
          'XZQH_XZ_PT_L',
        ],
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          12,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-padding': 2,
        'text-offset': [0, 0.5],
        'text-anchor': 'top',
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          '#686868',
          14,
          '#4E4E4E',
        ],
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'xzqh_xzjg_xz_x_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'xzqh_xzjg_pt',
      filter: ['match', ['get', 'jb'], ['乡镇级'], true, false],
      minzoom: 10,
      maxzoom: 11,
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          9,
          11,
          10,
          14,
          12,
          20,
          14,
        ],
        'text-max-angle': 38,
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          12,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-padding': 2,
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          '#686868',
          22,
          '#4E4E4E',
        ],
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'xzqh_xzjg_gwh_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'xzqh_xzjg_pt',
      filter: [
        'match',
        ['get', 'jb'],
        ['管委会(国家级)', '管委会(省级筹)'],
        true,
        false,
      ],
      minzoom: 10,
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          10,
          10,
          12,
          14,
          13,
          20,
          14,
        ],
        'icon-image': [
          'step',
          ['zoom'],
          '',
          10,
          'XZQH_GWH_PT_S',
          12,
          'XZQH_GWH_PT_M',
          14,
          'XZQH_GWH_PT_L',
        ],
        'text-max-angle': 38,
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          12,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-padding': 2,
        'text-offset': [0, 0.5],
        'text-anchor': 'top',
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          '#686868',
          22,
          '#4E4E4E',
        ],
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'xzqh_xzjg_qx_color',
      type: 'symbol',
      source: 'CSS_BaseMap',
      'source-layer': 'xzqh_xzjg_pt',
      filter: ['match', ['get', 'jb'], ['区县级'], true, false],
      minzoom: 10,
      layout: {
        'text-line-height': 1.1,
        'text-size': [
          'interpolate',
          ['linear'],
          ['zoom'],
          8,
          10,
          10,
          12,
          14,
          14,
          20,
          16,
        ],
        'icon-image': [
          'step',
          ['zoom'],
          '',
          10,
          'XZQH_QX_PT_S',
          12,
          'XZQH_QX_PT_M',
        ],
        'text-max-angle': 38,
        'text-font': [
          'step',
          ['zoom'],
          ['literal', ['MicrosoftYaHeiRegular']],
          10,
          ['literal', ['MicrosoftYaHeiBold']],
        ],
        'text-padding': 2,
        'text-offset': [0, 0.55],
        'text-anchor': 'top',
        'text-field': ['to-string', ['get', 'jc']],
        'text-max-width': 8,
      },
      paint: {
        'text-color': [
          'interpolate',
          ['linear'],
          ['zoom'],
          10,
          '#686868',
          12,
          '#4E4E4E',
        ],
        'text-halo-color': '#FFFFFF',
        'text-halo-width': 1.2,
      },
    },
  ],
}
